import { promises as fs } from "fs";
import path from "path";
import { transform } from "@svgr/core";

// base points to the package's src/ directory
const base = new URL("./", import.meta.url);
const svgDir = new URL("./svg/", base); // packages/youngro-icons/src/svg/
const generatedDir = new URL("./generated/", base); // packages/youngro-icons/src/generated/
const distReactDir = new URL("../dist/react/", base); // packages/youngro-icons/dist/react/

function pascalCase(name) {
  return name
    .replace(/(^|[-_\s]+)([a-zA-Z0-9])/g, (_, __, c) => (c || "").toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, "");
}

async function ensureDir(u) {
  try {
    await fs.mkdir(u, { recursive: true });
  } catch (e) {
    // ignore
  }
}

async function build() {
  await ensureDir(generatedDir);
  await ensureDir(distReactDir);

  const files = await fs.readdir(svgDir);
  const svgs = files.filter((f) => f.endsWith(".svg"));

  const exports = [];

  for (const file of svgs) {
    const name = path.basename(file, ".svg");
    const compName = pascalCase(name) + "Icon";
    const svgPath = new URL("./" + file, svgDir);
    const svg = await fs.readFile(svgPath, "utf8");

    const plugins = [
      "@svgr/plugin-svgo",
      "@svgr/plugin-jsx",
      "@svgr/plugin-prettier",
    ];

    const tsxComponent = await transform(
      svg,
      {
        icon: true,
        typescript: true,
        expandProps: "end",
        jsxRuntime: "automatic",
        prettier: false,
        plugins,
      },
      { componentName: compName }
    );
    const genPath = new URL("./" + compName + ".tsx", generatedDir);
    await fs.writeFile(genPath, tsxComponent.trim() + "\n", "utf8");

    const jsComponent = await transform(
      svg,
      {
        icon: true,
        typescript: false,
        expandProps: "end",
        jsxRuntime: "automatic",
        prettier: false,
        plugins,
      },
      { componentName: compName }
    );
    const distPath = new URL("./" + compName + ".js", distReactDir);
    await fs.writeFile(distPath, jsComponent.trim() + "\n", "utf8");

    exports.push({ name: compName });
  }

  const importLines = exports.map(
    (e) => `import ${e.name} from './${e.name}';`
  );
  const namedExportLine =
    exports.length > 0
      ? `export { ${exports.map((e) => e.name).join(", ")} };`
      : "export {};";

  const srcIndexLines = [
    "// Auto-generated by build-icons.mjs",
    ...importLines,
    "",
    namedExportLine,
    "",
    "const icons = {",
    ...exports.map((e) => `  ${e.name},`),
    "} as const;",
    "",
    "export default icons;",
    "",
  ];
  const srcIndexPath = new URL("./index.tsx", generatedDir);
  await fs.writeFile(srcIndexPath, srcIndexLines.join("\n"), "utf8");

  const dtsLines = [
    "import * as React from 'react';",
    "",
    ...exports.map(
      (e) =>
        `export declare const ${e.name}: React.FC<React.SVGProps<SVGSVGElement>>;`
    ),
    "",
    "declare const _default: {",
    ...exports.map((e) => `  ${e.name}: typeof ${e.name};`),
    "};",
    "export default _default;",
    "",
  ];
  const dtsPath = new URL("./index.d.ts", generatedDir);
  await fs.writeFile(dtsPath, dtsLines.join("\n"), "utf8");

  const distImportLines = exports.map(
    (e) => `import ${e.name} from './${e.name}.js';`
  );
  let distIdx = "";
  distIdx += distImportLines.join("\n") + "\n\n";
  distIdx +=
    (exports.length > 0
      ? `export { ${exports.map((e) => e.name).join(", ")} };`
      : "export {};") + "\n\n";
  distIdx +=
    "const icons = { " +
    exports.map((e) => `${e.name}`).join(", ") +
    " }\nexport default icons\n";
  const distIndexPath = new URL("./index.js", distReactDir);
  await fs.writeFile(distIndexPath, distIdx, "utf8");

  console.log("built react icons to", distReactDir.pathname);
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});
